// =============================================================================
// LESSON 7: Credit Card Fraud Detector -- GPU Rules Engine + Metrics
// =============================================================================
//
// Real-world shape:
//   Stage A: score every transaction (regular per-row math)
//   Stage B: reduce outcomes into operational metrics (TP/FP/TN/FN, histogram)
//
// This lesson intentionally includes a CPU baseline so you can observe the
// crossover point where GPU throughput wins vs where CPU overhead is lower.
// =============================================================================

use metal::*;
use objc::rc::autoreleasepool;
use std::env;
use std::ffi::CString;
use std::ptr;
use std::time::Instant;

// Default workload: intentionally huge so users can see CPU/GPU crossover.
const DEFAULT_TOTAL_TRANSACTIONS: u64 = 2_000_000_000;
// Print progress every N% of chunks.
const DEFAULT_PROGRESS_INTERVAL: u64 = 10;
// For auto chunking, use at most this fraction of detected RAM budget.
const DEFAULT_MEMORY_FRACTION: f64 = 0.85;
// Decision boundary for classification: score >= threshold => predicted fraud.
const DEFAULT_THRESHOLD: f32 = 0.72;
// Number of score histogram buckets to show distribution shape.
const DEFAULT_SCORE_BINS: u32 = 20;
// Multiplier on hidden fraud prevalence (ground truth generation only).
const DEFAULT_FRAUD_RATE_BOOST: f32 = 1.0;
// Fallback chunk size when RAM detection is unavailable.
const DEFAULT_FALLBACK_CHUNK_TRANSACTIONS: u64 = 4_000_000;
// One threadgroup has 256 threads in both kernels.
// This is a common power-of-two size that simplifies tree reductions.
const THREADGROUP_SIZE: u64 = 256;
// Safety cap so threadgroup histogram arrays have a fixed compile-time size.
const MAX_SCORE_BINS: u32 = 64;

const SHADER_SOURCE: &str = include_str!("lesson7.metal");

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Mode {
    // Fill -> submit -> wait for each chunk in sequence.
    Single,
    // Two slots; CPU fills one while GPU may process the other.
    Double,
}

impl Mode {
    fn as_str(self) -> &'static str {
        match self {
            Self::Single => "single",
            Self::Double => "double",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ValidationMode {
    // Recompute every chunk on CPU and compare with GPU outputs.
    Full,
    // Validate first and periodic chunks only (faster, still confidence).
    Spot,
    // Skip chunk-level CPU checks.
    Off,
}

impl ValidationMode {
    fn as_str(self) -> &'static str {
        match self {
            Self::Full => "full",
            Self::Spot => "spot",
            Self::Off => "off",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum CompareCpu {
    // Run a complete CPU baseline after GPU run for throughput comparison.
    On,
    // Skip CPU baseline timing.
    Off,
}

impl CompareCpu {
    fn as_str(self) -> &'static str {
        match self {
            Self::On => "on",
            Self::Off => "off",
        }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
struct KernelParams {
    // Number of valid transaction rows in current chunk.
    count: u32,
    // Histogram bins requested by user.
    score_bins: u32,
    // Fraud decision threshold.
    threshold: f32,
    // Padding for alignment parity with Metal struct.
    _pad0: u32,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
struct TransactionFeatures {
    // Raw transaction amount in synthetic currency units.
    amount: f32,
    // Hour of day [0, 23].
    hour_of_day: f32,
    // Distance from expected cardholder location.
    distance_km: f32,
    // 1.0 if physical card present, 0.0 otherwise.
    is_card_present: f32,
    // Merchant category risk prior in [0, 1].
    mcc_risk: f32,
    // Recent transaction count proxy (last hour).
    velocity_1h: f32,
    // 1.0 if country appears unusual for this user.
    country_mismatch: f32,
    // 1.0 if device recently changed.
    device_change: f32,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
struct ScoreOutput {
    // Predicted risk score in [0, 1].
    score: f32,
    // Predicted class from threshold.
    predicted_fraud: u32,
    // Ground-truth label generated by hidden rule.
    actual_fraud: u32,
    // Histogram bucket index for score.
    bin_index: u32,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
struct PartialMetrics {
    // Confusion matrix counts for one threadgroup's partial result.
    tp: u32,
    fp: u32,
    tn: u32,
    fn_: u32,
    // Sum of scores split by actual class, used for mean-score diagnostics.
    sum_score_legit: f32,
    sum_score_fraud: f32,
    // Denominators for those mean scores.
    count_legit: u32,
    count_fraud: u32,
}

#[derive(Clone, Debug)]
struct CliConfig {
    // Raw CLI values before device-aware chunk resolution.
    mode: Mode,
    total_transactions: u64,
    chunk_transactions_override: Option<u64>,
    memory_fraction: f64,
    progress_interval: u64,
    validation: ValidationMode,
    compare_cpu: CompareCpu,
    threshold: f32,
    score_bins: u32,
    fraud_rate_boost: f32,
}

#[derive(Clone, Debug)]
struct Config {
    // Resolved runtime config (includes derived chunk size and diagnostics).
    mode: Mode,
    total_transactions: u64,
    chunk_transactions: u64,
    memory_fraction: f64,
    progress_interval: u64,
    validation: ValidationMode,
    compare_cpu: CompareCpu,
    threshold: f32,
    score_bins: u32,
    fraud_rate_boost: f32,
    chunk_auto: bool,
    detected_ram_bytes: Option<u64>,
}

#[derive(Clone, Debug)]
struct AggregateTotals {
    // Global aggregate metrics over all processed transactions.
    tp: u64,
    fp: u64,
    tn: u64,
    fn_: u64,
    sum_score_legit: f64,
    sum_score_fraud: f64,
    count_legit: u64,
    count_fraud: u64,
    histogram: Vec<u64>,
}

#[derive(Clone, Copy, Debug)]
struct DerivedMetrics {
    // Standard quality metrics derived from aggregate confusion counts.
    precision: f64,
    recall: f64,
    fpr: f64,
    accuracy: f64,
    mean_score_legit: f64,
    mean_score_fraud: f64,
}

#[derive(Clone, Copy, Debug, Default)]
struct RunStats {
    // End-to-end runtime and rough phase breakdown.
    wall_s: f64,
    fill_s: f64,
    gpu_s: f64,
    transactions: u64,
}

struct InFlight {
    // Metadata to track one submitted chunk until GPU completion.
    command_buffer: CommandBuffer,
    slot: usize,
    chunk_index: u64,
    base_index: u64,
    len: usize,
    partial_groups: usize,
}

struct GpuPipelines {
    // Compiled GPU pipelines and queue reused across chunks.
    command_queue: CommandQueue,
    score_pipeline: ComputePipelineState,
    reduce_pipeline: ComputePipelineState,
}

struct SlotBuffers {
    // Per-slot buffers (double mode has 2 slots, single mode has 1).
    // Using struct-of-arrays keeps memory accesses regular in kernels.
    amounts: Buffer,
    hours: Buffer,
    distance_km: Buffer,
    is_card_present: Buffer,
    mcc_risk: Buffer,
    velocity_1h: Buffer,
    country_mismatch: Buffer,
    device_change: Buffer,
    actual_labels: Buffer,
    score_output: Buffer,
    partial_metrics: Buffer,
    partial_hist: Buffer,
    params: Buffer,
}

// Teaching note:
// This prints CLI help only; no compute work happens here.
// Keep this short so users can scan defaults quickly.
fn print_usage() {
    // Keep help compact so users can copy-paste quickly.
    println!("Usage: credit-card-fraud-detector [--mode single|double] [--total-transactions N] [--chunk-transactions N] [--memory-fraction F] [--progress-interval PCT] [--validate full|spot|off] [--compare-cpu on|off] [--threshold T] [--score-bins B] [--fraud-rate-boost X]");
    println!();
    println!("Defaults:");
    println!("  --mode double");
    println!("  --total-transactions {}", DEFAULT_TOTAL_TRANSACTIONS);
    println!("  --chunk-transactions auto");
    println!("  --memory-fraction {:.2}", DEFAULT_MEMORY_FRACTION);
    println!("  --progress-interval {}", DEFAULT_PROGRESS_INTERVAL);
    println!("  --validate spot");
    println!("  --compare-cpu on");
    println!("  --threshold {:.2}", DEFAULT_THRESHOLD);
    println!("  --score-bins {}", DEFAULT_SCORE_BINS);
    println!("  --fraud-rate-boost {:.2}", DEFAULT_FRAUD_RATE_BOOST);
}

// Teaching note:
// Small parser helper so parse errors can include the flag name.
fn parse_u64(name: &str, value: &str) -> Result<u64, String> {
    value
        .parse::<u64>()
        .map_err(|_| format!("Invalid value for {name}: '{value}'"))
}

// Teaching note:
// Same pattern as parse_u64, specialized by target type.
fn parse_u32(name: &str, value: &str) -> Result<u32, String> {
    value
        .parse::<u32>()
        .map_err(|_| format!("Invalid value for {name}: '{value}'"))
}

// Teaching note:
// Parsing is separated from validation so errors stay specific.
fn parse_f32(name: &str, value: &str) -> Result<f32, String> {
    value
        .parse::<f32>()
        .map_err(|_| format!("Invalid value for {name}: '{value}'"))
}

// Teaching note:
// f64 is used for memory-fraction because it may need more precision.
fn parse_f64(name: &str, value: &str) -> Result<f64, String> {
    value
        .parse::<f64>()
        .map_err(|_| format!("Invalid value for {name}: '{value}'"))
}

// Teaching note:
// parse_args() builds a raw config from CLI text.
// It does not inspect GPU hardware yet; that happens later.
fn parse_args() -> Result<CliConfig, String> {
    let mut mode = Mode::Double;
    let mut total_transactions = DEFAULT_TOTAL_TRANSACTIONS;
    let mut chunk_transactions_override = None;
    let mut memory_fraction = DEFAULT_MEMORY_FRACTION;
    let mut progress_interval = DEFAULT_PROGRESS_INTERVAL;
    let mut validation = ValidationMode::Spot;
    let mut compare_cpu = CompareCpu::On;
    let mut threshold = DEFAULT_THRESHOLD;
    let mut score_bins = DEFAULT_SCORE_BINS;
    let mut fraud_rate_boost = DEFAULT_FRAUD_RATE_BOOST;

    let args: Vec<String> = env::args().collect();
    let mut i = 1usize;

    // Simple manual parser: explicit and easy to read for beginners.
    while i < args.len() {
        match args[i].as_str() {
            "-h" | "--help" => {
                print_usage();
                std::process::exit(0);
            }
            "--mode" => {
                let v = args.get(i + 1).ok_or_else(|| "Missing value for --mode".to_string())?;
                mode = match v.as_str() {
                    "single" => Mode::Single,
                    "double" => Mode::Double,
                    _ => return Err(format!("Invalid --mode value '{v}'")),
                };
                i += 2;
            }
            "--total-transactions" => {
                let v = args
                    .get(i + 1)
                    .ok_or_else(|| "Missing value for --total-transactions".to_string())?;
                total_transactions = parse_u64("--total-transactions", v)?;
                i += 2;
            }
            "--chunk-transactions" => {
                let v = args
                    .get(i + 1)
                    .ok_or_else(|| "Missing value for --chunk-transactions".to_string())?;
                chunk_transactions_override = Some(parse_u64("--chunk-transactions", v)?);
                i += 2;
            }
            "--memory-fraction" => {
                let v = args
                    .get(i + 1)
                    .ok_or_else(|| "Missing value for --memory-fraction".to_string())?;
                memory_fraction = parse_f64("--memory-fraction", v)?;
                i += 2;
            }
            "--progress-interval" => {
                let v = args
                    .get(i + 1)
                    .ok_or_else(|| "Missing value for --progress-interval".to_string())?;
                progress_interval = parse_u64("--progress-interval", v)?;
                i += 2;
            }
            "--validate" => {
                let v = args
                    .get(i + 1)
                    .ok_or_else(|| "Missing value for --validate".to_string())?;
                validation = match v.as_str() {
                    "full" => ValidationMode::Full,
                    "spot" => ValidationMode::Spot,
                    "off" => ValidationMode::Off,
                    _ => return Err(format!("Invalid --validate value '{v}'")),
                };
                i += 2;
            }
            "--compare-cpu" => {
                let v = args
                    .get(i + 1)
                    .ok_or_else(|| "Missing value for --compare-cpu".to_string())?;
                compare_cpu = match v.as_str() {
                    "on" => CompareCpu::On,
                    "off" => CompareCpu::Off,
                    _ => return Err(format!("Invalid --compare-cpu value '{v}'")),
                };
                i += 2;
            }
            "--threshold" => {
                let v = args
                    .get(i + 1)
                    .ok_or_else(|| "Missing value for --threshold".to_string())?;
                threshold = parse_f32("--threshold", v)?;
                i += 2;
            }
            "--score-bins" => {
                let v = args
                    .get(i + 1)
                    .ok_or_else(|| "Missing value for --score-bins".to_string())?;
                score_bins = parse_u32("--score-bins", v)?;
                i += 2;
            }
            "--fraud-rate-boost" => {
                let v = args
                    .get(i + 1)
                    .ok_or_else(|| "Missing value for --fraud-rate-boost".to_string())?;
                fraud_rate_boost = parse_f32("--fraud-rate-boost", v)?;
                i += 2;
            }
            flag => return Err(format!("Unknown argument: {flag}")),
        }
    }

    if chunk_transactions_override == Some(0) {
        return Err("--chunk-transactions must be > 0".to_string());
    }
    // memory_fraction controls auto-chunk RAM budget.
    if !(memory_fraction > 0.0 && memory_fraction <= 1.0) {
        return Err("--memory-fraction must be in (0.0, 1.0]".to_string());
    }
    // progress interval is a UI concern only.
    if !(1..=100).contains(&progress_interval) {
        return Err("--progress-interval must be in 1..=100".to_string());
    }
    // threshold is a probability-like cutoff.
    if !(0.0..=1.0).contains(&threshold) {
        return Err("--threshold must be in [0.0, 1.0]".to_string());
    }
    if !(1..=MAX_SCORE_BINS).contains(&score_bins) {
        return Err(format!("--score-bins must be in 1..={MAX_SCORE_BINS}"));
    }
    if fraud_rate_boost <= 0.0 {
        return Err("--fraud-rate-boost must be > 0".to_string());
    }

    Ok(CliConfig {
        mode,
        total_transactions,
        chunk_transactions_override,
        memory_fraction,
        progress_interval,
        validation,
        compare_cpu,
        threshold,
        score_bins,
        fraud_rate_boost,
    })
}

// Teaching note:
// Returns total system RAM on macOS.
// Used only for auto chunk sizing; manual chunk mode ignores it.
fn detect_system_ram_bytes() -> Option<u64> {
    // macOS-specific probe used for auto chunk sizing.
    let mut ram_bytes: u64 = 0;
    let mut size = std::mem::size_of::<u64>();
    let name = CString::new("hw.memsize").ok()?;

    let rc = unsafe {
        libc::sysctlbyname(
            name.as_ptr(),
            (&mut ram_bytes as *mut u64).cast(),
            &mut size,
            ptr::null_mut(),
            0,
        )
    };

    if rc == 0 && size == std::mem::size_of::<u64>() {
        Some(ram_bytes)
    } else {
        None
    }
}

// Teaching note:
// Converts raw CLI config into runtime config using hardware constraints.
// Main objective: choose chunk size big enough for throughput, small enough
// to fit memory and Metal buffer limits.
fn resolve_chunk_transactions(cli: CliConfig, device: &Device) -> Config {
    let detected_ram_bytes = detect_system_ram_bytes();
    let max_buffer = device.max_buffer_length() as u128;

    let (chunk_transactions, chunk_auto) = if let Some(v) = cli.chunk_transactions_override {
        // Manual override takes precedence.
        (v, false)
    } else {
        // Rough capacity model:
        // 8 f32 feature buffers + 1 u32 label + score/partials overhead ~= 64 B/tx/slot.
        // Exact usage varies, but this heuristic keeps chunks practical and simple.
        let bytes_per_tx_per_slot = 64u128;
        let slot_count = match cli.mode {
            Mode::Single => 1u128,
            Mode::Double => 2u128,
        };

        let target_total = detected_ram_bytes
            .map(|r| (r as f64 * cli.memory_fraction) as u128)
            .unwrap_or(DEFAULT_FALLBACK_CHUNK_TRANSACTIONS as u128 * bytes_per_tx_per_slot * slot_count);

        // Budget is split across slots (single=1, double=2).
        let per_slot_budget = (target_total / slot_count).max(bytes_per_tx_per_slot);
        let max_by_ram = per_slot_budget / bytes_per_tx_per_slot;
        // Also obey Metal's max single-buffer length.
        let max_by_device = max_buffer / std::mem::size_of::<ScoreOutput>() as u128;

        let tx = max_by_ram
            .min(max_by_device)
            .min(cli.total_transactions as u128)
            .max(1) as u64;
        (tx, true)
    };

    Config {
        mode: cli.mode,
        total_transactions: cli.total_transactions,
        chunk_transactions,
        memory_fraction: cli.memory_fraction,
        progress_interval: cli.progress_interval,
        validation: cli.validation,
        compare_cpu: cli.compare_cpu,
        threshold: cli.threshold,
        score_bins: cli.score_bins,
        fraud_rate_boost: cli.fraud_rate_boost,
        chunk_auto,
        detected_ram_bytes,
    }
}

// Teaching note:
// In spot-validation mode we check first/end/progress checkpoints.
fn should_spot_check(chunk_index: u64, total_chunks: u64, progress_step_chunks: u64) -> bool {
    // Spot-check end-of-run and each progress checkpoint.
    chunk_index + 1 == total_chunks || (chunk_index + 1) % progress_step_chunks == 0
}

// Teaching note:
// Human-facing progress logger for long runs.
fn print_progress(chunk_index: u64, total_chunks: u64, total: u64, chunk: u64, start: Instant) {
    // Show processed amount and elapsed time so users can estimate ETA.
    let done = (chunk_index + 1).saturating_mul(chunk).min(total);
    let pct = if total == 0 {
        100.0
    } else {
        done as f64 / total as f64 * 100.0
    };

    println!(
        "  Chunk {:>6}/{}: {:>7.2}M tx ({:>5.1}%) - {:>7.2}s",
        chunk_index + 1,
        total_chunks,
        done as f64 / 1e6,
        pct,
        start.elapsed().as_secs_f64()
    );
}

// Teaching note:
// Generates one synthetic transaction from an index.
// Think of `idx` as row-id in an infinite deterministic dataset.
fn transaction_features(idx: u64) -> TransactionFeatures {
    // Deterministic synthetic stream: same idx => same transaction every run.
    // This keeps benchmarks reproducible for learning and comparison.
    let amount = {
        let base = ((idx.wrapping_mul(48271).wrapping_add(12345)) % 10_000) as f32 / 10.0;
        // Occasional spikes simulate rare high-amount purchases.
        let spike = if idx % 97 == 0 { 900.0 } else { 0.0 };
        1.0 + base + spike
    };

    // Each feature uses a different pattern/period so correlations are imperfect.
    let hour_of_day = ((idx.wrapping_mul(13).wrapping_add(5)) % 24) as f32;
    let distance_km = ((idx.wrapping_mul(71).wrapping_add(11)) % 3000) as f32 * 0.5;
    let is_card_present = if idx % 5 == 0 { 0.0 } else { 1.0 };
    let mcc_risk = ((idx.wrapping_mul(17).wrapping_add(3)) % 100) as f32 / 100.0;
    let velocity_1h = ((idx.wrapping_mul(29).wrapping_add(7)) % 36) as f32;
    let country_mismatch = if idx % 19 == 0 { 1.0 } else { 0.0 };
    let device_change = if idx % 23 == 0 { 1.0 } else { 0.0 };

    TransactionFeatures {
        amount,
        hour_of_day,
        distance_km,
        is_card_present,
        mcc_risk,
        velocity_1h,
        country_mismatch,
        device_change,
    }
}

// Teaching note:
// Creates ground-truth labels ("actual fraud").
// This is separate from score_transaction() on purpose so evaluation is real:
// model predicts with one rule, truth comes from another rule.
fn hidden_fraud_label(f: &TransactionFeatures, idx: u64, fraud_rate_boost: f32) -> u32 {
    // "Actual fraud" rule used as ground truth for evaluation.
    // It is intentionally separate from score_transaction() to avoid leakage.
    let amount_high = if f.amount > 1200.0 { 1.0 } else { 0.0 };
    let velocity_high = if f.velocity_1h > 16.0 { 1.0 } else { 0.0 };
    let night = if f.hour_of_day < 6.0 || f.hour_of_day > 22.0 {
        1.0
    } else {
        0.0
    };

    let mut risk = 0.01 * fraud_rate_boost;
    // High-risk combination: unusual country + new device + large amount.
    risk += 0.35 * f.country_mismatch * f.device_change * amount_high;
    // Fast spending without card present is suspicious.
    risk += 0.22 * velocity_high * (1.0 - f.is_card_present);
    // Off-hours + risky merchant adds moderate risk.
    risk += 0.10 * night * f.mcc_risk;
    // Far-distance + card-not-present contributes additional risk.
    risk += 0.08 * (f.distance_km / 1500.0).min(1.0) * (1.0 - f.is_card_present);

    // Convert idx into a deterministic pseudo-random value in [0, 1).
    // This introduces noise while still being reproducible.
    let h = ((idx.wrapping_mul(1_103_515_245).wrapping_add(12_345)) >> 8) % 10_000;
    let p = (h as f32) / 10_000.0;

    // Bernoulli draw from computed risk (capped to avoid degenerate 100% fraud).
    if p < risk.min(0.95) { 1 } else { 0 }
}

// Teaching note:
// Model-like scoring function used for prediction.
// Returns a soft risk score in [0, 1], then thresholding creates class label.
fn score_transaction(f: &TransactionFeatures) -> f32 {
    // Normalize raw fields into 0..1 ranges before weighting.
    let amount_n = (f.amount / 2000.0).clamp(0.0, 1.0);
    // Off-hours are a mild risk signal in this toy policy.
    let off_hours = if f.hour_of_day < 6.0 || f.hour_of_day > 22.0 {
        1.0
    } else {
        0.0
    };
    let distance_n = (f.distance_km / 1500.0).clamp(0.0, 1.0);
    let card_not_present = 1.0 - f.is_card_present;
    let velocity_n = (f.velocity_1h / 24.0).clamp(0.0, 1.0);

    // Weighted rules engine.
    // Why these terms:
    // - amount/velocity/card-not-present capture transactional behavior
    // - mcc/country/device capture context anomalies
    // - interaction terms represent risk that appears only in combinations
    let mut score = 0.05;
    score += 0.20 * amount_n;
    score += 0.08 * off_hours;
    score += 0.14 * distance_n;
    score += 0.18 * card_not_present;
    score += 0.14 * velocity_n;
    score += 0.10 * f.mcc_risk;
    score += 0.17 * f.country_mismatch;
    score += 0.14 * f.device_change;
    score += 0.10 * f.country_mismatch * f.device_change;
    score += 0.08 * card_not_present * velocity_n;

    // Score is clipped to [0,1] so thresholding and histogram bins are stable.
    score.clamp(0.0, 1.0)
}

// Teaching note:
// Maps continuous score to a histogram bucket index.
fn score_bin(score: f32, bins: u32) -> u32 {
    // Convert score in [0,1] into integer bucket index.
    let b = bins.max(1).min(MAX_SCORE_BINS);
    let idx = (score * b as f32) as u32;
    idx.min(b - 1)
}

// Teaching note:
// Creates a zeroed accumulator object for metrics.
fn empty_totals(bins: u32) -> AggregateTotals {
    // Zero-initialized metric accumulator for one chunk or full run.
    AggregateTotals {
        tp: 0,
        fp: 0,
        tn: 0,
        fn_: 0,
        sum_score_legit: 0.0,
        sum_score_fraud: 0.0,
        count_legit: 0,
        count_fraud: 0,
        histogram: vec![0; bins as usize],
    }
}

// Teaching note:
// CPU reference path for one contiguous transaction range.
// This is the "golden" implementation used for correctness checks.
fn aggregate_range(base_index: u64, len: usize, config: &Config) -> AggregateTotals {
    let mut out = empty_totals(config.score_bins);

    // CPU reference implementation:
    // evaluate each transaction, classify it, and accumulate metrics.
    for i in 0..len {
        let idx = base_index + i as u64;
        let f = transaction_features(idx);
        let actual = hidden_fraud_label(&f, idx, config.fraud_rate_boost);
        let score = score_transaction(&f);
        let pred = if score >= config.threshold { 1 } else { 0 };

        // Confusion matrix tracks classification outcomes.
        match (pred, actual) {
            (1, 1) => out.tp += 1,
            (1, 0) => out.fp += 1,
            (0, 0) => out.tn += 1,
            (0, 1) => out.fn_ += 1,
            _ => unreachable!(),
        }

        if actual == 1 {
            // Split by actual label so mean-score diagnostics are meaningful.
            out.sum_score_fraud += score as f64;
            out.count_fraud += 1;
        } else {
            out.sum_score_legit += score as f64;
            out.count_legit += 1;
        }

        let b = score_bin(score, config.score_bins) as usize;
        // Histogram supports threshold tuning and score-separation analysis.
        out.histogram[b] += 1;
    }

    out
}

// Teaching note:
// Associative reduction: combines one accumulator into another.
// This exact pattern is why map-reduce style GPU processing works well here.
fn merge_totals(dst: &mut AggregateTotals, src: &AggregateTotals) {
    // Metric reductions are associative additions; perfect for chunking/GPU.
    dst.tp += src.tp;
    dst.fp += src.fp;
    dst.tn += src.tn;
    dst.fn_ += src.fn_;
    dst.sum_score_legit += src.sum_score_legit;
    dst.sum_score_fraud += src.sum_score_fraud;
    dst.count_legit += src.count_legit;
    dst.count_fraud += src.count_fraud;

    for (d, s) in dst.histogram.iter_mut().zip(src.histogram.iter()) {
        *d += *s;
    }
}

// Teaching note:
// Converts raw confusion counts/sums into standard metrics.
// This function is pure post-processing; no GPU interaction.
fn metrics_from_totals(t: &AggregateTotals) -> DerivedMetrics {
    let tp = t.tp as f64;
    let fp = t.fp as f64;
    let tn = t.tn as f64;
    let fn_ = t.fn_ as f64;
    let total = tp + fp + tn + fn_;

    DerivedMetrics {
        // Precision: among predicted fraud, fraction truly fraud.
        precision: if tp + fp > 0.0 { tp / (tp + fp) } else { 0.0 },
        // Recall: among actual fraud, fraction detected.
        recall: if tp + fn_ > 0.0 { tp / (tp + fn_) } else { 0.0 },
        // False Positive Rate: among legitimate tx, fraction flagged.
        fpr: if fp + tn > 0.0 { fp / (fp + tn) } else { 0.0 },
        // Accuracy: fraction of all correct predictions.
        accuracy: if total > 0.0 { (tp + tn) / total } else { 0.0 },
        mean_score_legit: if t.count_legit > 0 {
            t.sum_score_legit / t.count_legit as f64
        } else {
            0.0
        },
        mean_score_fraud: if t.count_fraud > 0 {
            t.sum_score_fraud / t.count_fraud as f64
        } else {
            0.0
        },
    }
}

// Teaching note:
// Validates CPU and GPU aggregates are effectively the same.
// Integer counts should match exactly; float-derived values allow tiny tolerance.
fn assert_totals_close(expected: &AggregateTotals, got: &AggregateTotals, label: &str) -> Result<(), String> {
    // Exact checks for integer counts: these should match bit-for-bit.
    let exact = |name: &str, a: u64, b: u64| -> Result<(), String> {
        if a != b {
            return Err(format!("{label}: {name} mismatch, expected {a}, got {b}"));
        }
        Ok(())
    };

    exact("tp", expected.tp, got.tp)?;
    exact("fp", expected.fp, got.fp)?;
    exact("tn", expected.tn, got.tn)?;
    exact("fn", expected.fn_, got.fn_)?;
    exact("count_legit", expected.count_legit, got.count_legit)?;
    exact("count_fraud", expected.count_fraud, got.count_fraud)?;

    let hist_total: u64 = expected.histogram.iter().sum();
    // Histogram tolerances:
    // CPU/GPU may differ by a few ULPs in floating-point score computation.
    // Values near a bin edge can fall into neighboring bins differently.
    // We allow tiny drift that scales with dataset size.
    let per_bin_tolerance: i64 = ((hist_total / 1_000_000).max(2)) as i64;
    let mut total_hist_drift: i64 = 0;
    for (i, (a, b)) in expected.histogram.iter().zip(got.histogram.iter()).enumerate() {
        let diff = (*a as i64 - *b as i64).abs();
        total_hist_drift += diff;
        if diff > per_bin_tolerance {
            return Err(format!(
                "{label}: histogram bin {i} mismatch, expected {a}, got {b}, diff {diff} > {per_bin_tolerance}"
            ));
        }
    }
    let total_hist_tolerance: i64 = ((hist_total / 100_000).max(10)) as i64;
    if total_hist_drift > total_hist_tolerance {
        return Err(format!(
            "{label}: aggregate histogram drift too high, diff {total_hist_drift} > {total_hist_tolerance}"
        ));
    }

    // Float sum tolerances:
    // - absolute floor handles very small totals
    // - relative term scales with magnitude for large totals
    let check_f = |name: &str, a: f64, b: f64| -> Result<(), String> {
        let tol_abs = 0.05f64;
        let tol_rel = 5e-4f64;
        let allowed = tol_abs.max(a.abs() * tol_rel);
        let diff = (a - b).abs();
        if diff > allowed {
            return Err(format!(
                "{label}: {name} mismatch, expected {:.6}, got {:.6}, diff {:.6} > {:.6}",
                a, b, diff, allowed
            ));
        }
        Ok(())
    };

    check_f("sum_score_legit", expected.sum_score_legit, got.sum_score_legit)?;
    check_f("sum_score_fraud", expected.sum_score_fraud, got.sum_score_fraud)?;

    Ok(())
}

// Teaching note:
// CPU writes one chunk of feature columns + labels into shared buffers.
// These shared buffers are then read directly by GPU kernels.
fn fill_chunk_features(
    base_index: u64,
    len: usize,
    fraud_rate_boost: f32,
    amounts: *mut f32,
    hours: *mut f32,
    distance_km: *mut f32,
    is_card_present: *mut f32,
    mcc_risk: *mut f32,
    velocity_1h: *mut f32,
    country_mismatch: *mut f32,
    device_change: *mut f32,
    actual_labels: *mut u32,
) {
    unsafe {
        // Fill contiguous column buffers for this chunk.
        // Layout is "struct of arrays": one buffer per feature.
        // Why SoA:
        // GPU threads reading one feature across many rows access contiguous
        // memory, improving cache/coalescing behavior.
        for i in 0..len {
            let idx = base_index + i as u64;
            let f = transaction_features(idx);
            let label = hidden_fraud_label(&f, idx, fraud_rate_boost);

            amounts.add(i).write(f.amount);
            hours.add(i).write(f.hour_of_day);
            distance_km.add(i).write(f.distance_km);
            is_card_present.add(i).write(f.is_card_present);
            mcc_risk.add(i).write(f.mcc_risk);
            velocity_1h.add(i).write(f.velocity_1h);
            country_mismatch.add(i).write(f.country_mismatch);
            device_change.add(i).write(f.device_change);
            actual_labels.add(i).write(label);
        }
    }
}

// Teaching note:
// Encodes the two-kernel GPU workflow for one chunk:
// 1) score each row
// 2) reduce rows into per-threadgroup partial metrics
// Returns a command buffer handle so caller can wait later.
fn encode_chunk(
    gpu: &GpuPipelines,
    slot: &SlotBuffers,
    chunk_len: usize,
    partial_groups: usize,
) -> CommandBuffer {
    // Build one Metal command buffer with two compute stages:
    // Stage A scores each transaction, Stage B reduces metrics.
    let cb = gpu.command_queue.new_command_buffer().to_owned();

    let stage_a = cb.new_compute_command_encoder();
    // Stage A binding layout mirrors lesson7.metal `score_transactions`.
    stage_a.set_compute_pipeline_state(&gpu.score_pipeline);
    stage_a.set_buffer(0, Some(&slot.amounts), 0);
    stage_a.set_buffer(1, Some(&slot.hours), 0);
    stage_a.set_buffer(2, Some(&slot.distance_km), 0);
    stage_a.set_buffer(3, Some(&slot.is_card_present), 0);
    stage_a.set_buffer(4, Some(&slot.mcc_risk), 0);
    stage_a.set_buffer(5, Some(&slot.velocity_1h), 0);
    stage_a.set_buffer(6, Some(&slot.country_mismatch), 0);
    stage_a.set_buffer(7, Some(&slot.device_change), 0);
    stage_a.set_buffer(8, Some(&slot.actual_labels), 0);
    stage_a.set_buffer(9, Some(&slot.score_output), 0);
    stage_a.set_buffer(10, Some(&slot.params), 0);
    // One thread per transaction for scoring.
    // dispatch_threads handles non-multiples of THREADGROUP_SIZE safely.
    stage_a.dispatch_threads(
        MTLSize::new(chunk_len as u64, 1, 1),
        MTLSize::new(THREADGROUP_SIZE, 1, 1),
    );
    stage_a.end_encoding();

    let stage_b = cb.new_compute_command_encoder();
    // Stage B binding layout mirrors lesson7.metal `reduce_metrics`.
    stage_b.set_compute_pipeline_state(&gpu.reduce_pipeline);
    stage_b.set_buffer(0, Some(&slot.score_output), 0);
    stage_b.set_buffer(1, Some(&slot.partial_metrics), 0);
    stage_b.set_buffer(2, Some(&slot.partial_hist), 0);
    stage_b.set_buffer(3, Some(&slot.params), 0);
    // One threadgroup writes one partial aggregate record.
    // total partial groups == ceil(chunk_len / THREADGROUP_SIZE).
    stage_b.dispatch_thread_groups(
        MTLSize::new(partial_groups as u64, 1, 1),
        MTLSize::new(THREADGROUP_SIZE, 1, 1),
    );
    stage_b.end_encoding();

    cb.commit();
    cb
}

// Teaching note:
// After GPU finishes a chunk, this folds per-threadgroup partials into
// one chunk-level aggregate on CPU.
fn fold_slot_partials(slot: &SlotBuffers, partial_groups: usize, score_bins: u32) -> AggregateTotals {
    let mut out = empty_totals(score_bins);

    let partial_ptr = slot.partial_metrics.contents() as *const PartialMetrics;
    // Safe because buffer was allocated for exactly this many partial groups.
    let partials = unsafe { std::slice::from_raw_parts(partial_ptr, partial_groups) };

    // Fold partial confusion/sum counts from all threadgroups.
    for p in partials {
        out.tp += p.tp as u64;
        out.fp += p.fp as u64;
        out.tn += p.tn as u64;
        out.fn_ += p.fn_ as u64;
        out.sum_score_legit += p.sum_score_legit as f64;
        out.sum_score_fraud += p.sum_score_fraud as f64;
        out.count_legit += p.count_legit as u64;
        out.count_fraud += p.count_fraud as u64;
    }

    let hist_len = partial_groups * score_bins as usize;
    let hist_ptr = slot.partial_hist.contents() as *const u32;
    // Same safety argument for histogram slices.
    let hist = unsafe { std::slice::from_raw_parts(hist_ptr, hist_len) };

    // Fold each threadgroup's histogram slice into one global histogram.
    for g in 0..partial_groups {
        let row = &hist[g * score_bins as usize..(g + 1) * score_bins as usize];
        for (b, v) in row.iter().enumerate() {
            out.histogram[b] += *v as u64;
        }
    }

    out
}

// Teaching note:
// Completes one in-flight chunk:
// wait for GPU -> fold partials -> optional validate -> merge global totals.
fn finalize_in_flight(
    done: InFlight,
    slots: &[SlotBuffers],
    config: &Config,
    total_chunks: u64,
    progress_step_chunks: u64,
    start: Instant,
    gpu_s: &mut f64,
    global: &mut AggregateTotals,
) -> Result<(), String> {
    // Ensure GPU work for this chunk is complete before reading results.
    let wait_start = Instant::now();
    done.command_buffer.wait_until_completed();
    *gpu_s += wait_start.elapsed().as_secs_f64();

    let chunk_gpu = fold_slot_partials(&slots[done.slot], done.partial_groups, config.score_bins);

    let do_validate = match config.validation {
        ValidationMode::Off => false,
        ValidationMode::Full => true,
        ValidationMode::Spot => {
            done.chunk_index == 0
                || should_spot_check(done.chunk_index, total_chunks, progress_step_chunks)
        }
    };

    if do_validate {
        // Optional CPU-vs-GPU chunk check for correctness confidence.
        // Full mode: every chunk. Spot mode: first + periodic checkpoints.
        let expected = aggregate_range(done.base_index, done.len, config);
        assert_totals_close(&expected, &chunk_gpu, &format!("chunk {}", done.chunk_index + 1))?;
    }

    merge_totals(global, &chunk_gpu);

    if should_spot_check(done.chunk_index, total_chunks, progress_step_chunks) {
        print_progress(
            done.chunk_index,
            total_chunks,
            config.total_transactions,
            config.chunk_transactions,
            start,
        );
    }

    Ok(())
}

// Teaching note:
// Single-buffer schedule:
// fill chunk, launch chunk, wait chunk, repeat.
// Easy to understand, less overlap.
fn run_single(config: &Config, gpu: &GpuPipelines, slots: &[SlotBuffers]) -> Result<(RunStats, AggregateTotals), String> {
    let total_chunks = config.total_transactions.div_ceil(config.chunk_transactions);
    let progress_step_chunks = ((total_chunks * config.progress_interval) / 100).max(1);

    let slot = &slots[0];
    let amounts = slot.amounts.contents() as *mut f32;
    let hours = slot.hours.contents() as *mut f32;
    let distance_km = slot.distance_km.contents() as *mut f32;
    let is_card_present = slot.is_card_present.contents() as *mut f32;
    let mcc_risk = slot.mcc_risk.contents() as *mut f32;
    let velocity_1h = slot.velocity_1h.contents() as *mut f32;
    let country_mismatch = slot.country_mismatch.contents() as *mut f32;
    let device_change = slot.device_change.contents() as *mut f32;
    let labels = slot.actual_labels.contents() as *mut u32;
    let params = slot.params.contents() as *mut KernelParams;

    let start = Instant::now();
    let mut fill_s = 0.0;
    let mut gpu_s = 0.0;
    let mut global = empty_totals(config.score_bins);

    // Single mode is easiest to reason about, but cannot overlap CPU/GPU work.
    for chunk_index in 0..total_chunks {
        let base_index = chunk_index * config.chunk_transactions;
        let len = ((config.total_transactions - base_index).min(config.chunk_transactions)) as usize;
        let partial_groups = len.div_ceil(THREADGROUP_SIZE as usize).max(1);

        // 1) CPU prepares chunk inputs.
        let fill_start = Instant::now();
        fill_chunk_features(
            base_index,
            len,
            config.fraud_rate_boost,
            amounts,
            hours,
            distance_km,
            is_card_present,
            mcc_risk,
            velocity_1h,
            country_mismatch,
            device_change,
            labels,
        );
        unsafe {
            // Params buffer is read by both kernels in this command buffer.
            params.write(KernelParams {
                count: len as u32,
                score_bins: config.score_bins,
                threshold: config.threshold,
                _pad0: 0,
            });
        }
        fill_s += fill_start.elapsed().as_secs_f64();

        // 2) Submit GPU work.
        let submit_start = Instant::now();
        let command_buffer = encode_chunk(gpu, slot, len, partial_groups);
        gpu_s += submit_start.elapsed().as_secs_f64();

        // 3) Wait and fold results immediately (no overlap in single mode).
        finalize_in_flight(
            InFlight {
                command_buffer,
                slot: 0,
                chunk_index,
                base_index,
                len,
                partial_groups,
            },
            slots,
            config,
            total_chunks,
            progress_step_chunks,
            start,
            &mut gpu_s,
            &mut global,
        )?;
    }

    Ok((
        RunStats {
            wall_s: start.elapsed().as_secs_f64(),
            fill_s,
            gpu_s,
            transactions: config.total_transactions,
        },
        global,
    ))
}

// Teaching note:
// Double-buffer schedule (ping-pong):
// while GPU works on slot A, CPU fills slot B, then swap.
// Goal is overlap, reducing idle gaps between chunks.
fn run_double(config: &Config, gpu: &GpuPipelines, slots: &[SlotBuffers]) -> Result<(RunStats, AggregateTotals), String> {
    let total_chunks = config.total_transactions.div_ceil(config.chunk_transactions);
    let progress_step_chunks = ((total_chunks * config.progress_interval) / 100).max(1);

    let mut amounts = [std::ptr::null_mut::<f32>(); 2];
    let mut hours = [std::ptr::null_mut::<f32>(); 2];
    let mut distance_km = [std::ptr::null_mut::<f32>(); 2];
    let mut is_card_present = [std::ptr::null_mut::<f32>(); 2];
    let mut mcc_risk = [std::ptr::null_mut::<f32>(); 2];
    let mut velocity_1h = [std::ptr::null_mut::<f32>(); 2];
    let mut country_mismatch = [std::ptr::null_mut::<f32>(); 2];
    let mut device_change = [std::ptr::null_mut::<f32>(); 2];
    let mut labels = [std::ptr::null_mut::<u32>(); 2];
    let mut params = [std::ptr::null_mut::<KernelParams>(); 2];

    // Cache raw pointers per slot to avoid repeated casts in hot loop.
    for slot in 0..2 {
        amounts[slot] = slots[slot].amounts.contents() as *mut f32;
        hours[slot] = slots[slot].hours.contents() as *mut f32;
        distance_km[slot] = slots[slot].distance_km.contents() as *mut f32;
        is_card_present[slot] = slots[slot].is_card_present.contents() as *mut f32;
        mcc_risk[slot] = slots[slot].mcc_risk.contents() as *mut f32;
        velocity_1h[slot] = slots[slot].velocity_1h.contents() as *mut f32;
        country_mismatch[slot] = slots[slot].country_mismatch.contents() as *mut f32;
        device_change[slot] = slots[slot].device_change.contents() as *mut f32;
        labels[slot] = slots[slot].actual_labels.contents() as *mut u32;
        params[slot] = slots[slot].params.contents() as *mut KernelParams;
    }

    let start = Instant::now();
    let mut fill_s = 0.0;
    let mut gpu_s = 0.0;
    let mut global = empty_totals(config.score_bins);
    // Tracks command currently using each slot.
    let mut in_flight: [Option<InFlight>; 2] = [None, None];

    for chunk_index in 0..total_chunks {
        // Ping-pong between slot 0 and slot 1.
        let slot_idx = (chunk_index % 2) as usize;

        // Reusing a slot means its previous GPU command must be done first.
        if let Some(done) = in_flight[slot_idx].take() {
            finalize_in_flight(
                done,
                slots,
                config,
                total_chunks,
                progress_step_chunks,
                start,
                &mut gpu_s,
                &mut global,
            )?;
        }

        let base_index = chunk_index * config.chunk_transactions;
        let len = ((config.total_transactions - base_index).min(config.chunk_transactions)) as usize;
        let partial_groups = len.div_ceil(THREADGROUP_SIZE as usize).max(1);

        // While the other slot may still be running on GPU,
        // CPU fills this slot with the next chunk.
        let fill_start = Instant::now();
        fill_chunk_features(
            base_index,
            len,
            config.fraud_rate_boost,
            amounts[slot_idx],
            hours[slot_idx],
            distance_km[slot_idx],
            is_card_present[slot_idx],
            mcc_risk[slot_idx],
            velocity_1h[slot_idx],
            country_mismatch[slot_idx],
            device_change[slot_idx],
            labels[slot_idx],
        );
        unsafe {
            params[slot_idx].write(KernelParams {
                count: len as u32,
                score_bins: config.score_bins,
                threshold: config.threshold,
                _pad0: 0,
            });
        }
        fill_s += fill_start.elapsed().as_secs_f64();

        let submit_start = Instant::now();
        let command_buffer = encode_chunk(gpu, &slots[slot_idx], len, partial_groups);
        gpu_s += submit_start.elapsed().as_secs_f64();

        // Mark this slot as now running on GPU.
        in_flight[slot_idx] = Some(InFlight {
            command_buffer,
            slot: slot_idx,
            chunk_index,
            base_index,
            len,
            partial_groups,
        });
    }

    // Drain any remaining GPU work after all chunks are submitted.
    // Needed because last submitted chunk(s) may still be executing.
    while in_flight[0].is_some() || in_flight[1].is_some() {
        let slot_idx = match (&in_flight[0], &in_flight[1]) {
            (Some(a), Some(b)) => {
                if a.chunk_index <= b.chunk_index {
                    0
                } else {
                    1
                }
            }
            (Some(_), None) => 0,
            (None, Some(_)) => 1,
            (None, None) => unreachable!(),
        };

        if let Some(done) = in_flight[slot_idx].take() {
            finalize_in_flight(
                done,
                slots,
                config,
                total_chunks,
                progress_step_chunks,
                start,
                &mut gpu_s,
                &mut global,
            )?;
        }
    }

    Ok((
        RunStats {
            wall_s: start.elapsed().as_secs_f64(),
            fill_s,
            gpu_s,
            transactions: config.total_transactions,
        },
        global,
    ))
}

// Teaching note:
// CPU-only baseline for throughput comparison.
// Useful to find crossover point where GPU starts to win.
fn run_cpu_baseline(config: &Config) -> (f64, AggregateTotals) {
    let mut total = empty_totals(config.score_bins);
    let start = Instant::now();

    // Pure CPU path used to compare throughput and validate consistency.
    let mut done = 0u64;
    while done < config.total_transactions {
        // Baseline uses same chunk size so comparison is apples-to-apples.
        let len = (config.total_transactions - done).min(config.chunk_transactions) as usize;
        let chunk = aggregate_range(done, len, config);
        merge_totals(&mut total, &chunk);
        done += len as u64;
    }

    (start.elapsed().as_secs_f64(), total)
}

// Teaching note:
// Prints raw histogram counts by bin.
fn print_histogram(hist: &[u64]) {
    // Printed as raw counts (not percentages) to keep output unambiguous.
    println!("Score histogram:");
    for (i, v) in hist.iter().enumerate() {
        println!("  bin {:>2}: {}", i, v);
    }
}

// Teaching note:
// Final report printer: timings, quality metrics, histogram, and optional
// CPU-vs-GPU throughput/sanity comparison.
fn print_summary(config: &Config, gpu_stats: RunStats, gpu_totals: &AggregateTotals, cpu: Option<(f64, AggregateTotals)>) {
    let m = metrics_from_totals(gpu_totals);

    println!();
    println!("============================================================");
    println!(" Lesson 07 Results");
    println!("============================================================");
    println!("Mode:                {}", config.mode.as_str());
    println!("Validation:          {}", config.validation.as_str());
    println!("CPU baseline:        {}", config.compare_cpu.as_str());
    println!("Threshold:           {:.3}", config.threshold);
    println!("Score bins:          {}", config.score_bins);
    println!("Fraud rate boost:    {:.3}", config.fraud_rate_boost);

    println!("GPU wall time:       {:>9.3}s", gpu_stats.wall_s);
    println!(
        "GPU submit/wait:     {:>9.3}s ({:>5.1}%)",
        gpu_stats.gpu_s,
        (gpu_stats.gpu_s / gpu_stats.wall_s) * 100.0
    );
    // `fill_s` is CPU preprocessing time (feature + label generation).
    println!(
        "CPU fill time:       {:>9.3}s ({:>5.1}%)",
        gpu_stats.fill_s,
        (gpu_stats.fill_s / gpu_stats.wall_s) * 100.0
    );
    println!(
        "GPU throughput:      {:>9.3} million tx/sec",
        gpu_stats.transactions as f64 / 1e6 / gpu_stats.wall_s
    );

    println!();
    println!("Confusion matrix:");
    println!("  TP: {}", gpu_totals.tp);
    println!("  FP: {}", gpu_totals.fp);
    println!("  TN: {}", gpu_totals.tn);
    println!("  FN: {}", gpu_totals.fn_);

    println!();
    println!("Quality metrics:");
    println!("  Precision:          {:.6}", m.precision);
    println!("  Recall:             {:.6}", m.recall);
    println!("  FPR:                {:.6}", m.fpr);
    println!("  Accuracy:           {:.6}", m.accuracy);
    println!("  Mean legit score:   {:.6}", m.mean_score_legit);
    println!("  Mean fraud score:   {:.6}", m.mean_score_fraud);

    println!();
    print_histogram(&gpu_totals.histogram);

    let total = gpu_totals.tp + gpu_totals.fp + gpu_totals.tn + gpu_totals.fn_;
    println!();
    println!("Sanity checks:");
    println!(
        "  tp+fp+tn+fn == total: {} == {} ({})",
        total,
        config.total_transactions,
        if total == config.total_transactions {
            "ok"
        } else {
            "mismatch"
        }
    );
    let hist_total: u64 = gpu_totals.histogram.iter().sum();
    println!(
        "  histogram sum == total: {} == {} ({})",
        hist_total,
        config.total_transactions,
        if hist_total == config.total_transactions {
            "ok"
        } else {
            "mismatch"
        }
    );

    if let Some((cpu_s, cpu_totals)) = cpu {
        println!();
        println!("CPU baseline:");
        println!("  CPU time:           {:>9.3}s", cpu_s);
        println!(
            "  CPU throughput:     {:>9.3} million tx/sec",
            gpu_stats.transactions as f64 / 1e6 / cpu_s
        );
        // >1.0 means GPU is faster; <1.0 means CPU is faster for this workload.
        println!("  Speedup (CPU/GPU):  {:>9.3}x", cpu_s / gpu_stats.wall_s);

        match assert_totals_close(&cpu_totals, gpu_totals, "global totals") {
            Ok(()) => println!("  CPU/GPU metric consistency: ok"),
            Err(e) => println!("  CPU/GPU metric consistency: WARNING ({e})"),
        }
    }

    println!();
    println!("When GPU is better:");
    println!("  - huge regular batches with associative reductions");
    println!("  - overlap enabled (double mode) and enough work per chunk");
    println!("When CPU is better:");
    println!("  - small/latency-sensitive batches");
    println!("  - highly branchy logic and frequent synchronization");
}

// Teaching note:
// Program entry:
// parse CLI -> resolve chunking -> compile kernels -> allocate buffers ->
// run GPU pipeline -> optional CPU baseline -> print summary.
fn main() {
    autoreleasepool(|| {
        // Parse CLI first so we can fail fast on invalid inputs.
        let cli = match parse_args() {
            Ok(v) => v,
            Err(err) => {
                eprintln!("Argument error: {err}");
                eprintln!();
                print_usage();
                std::process::exit(2);
            }
        };

        if cli.total_transactions == 0 {
            println!("No work requested (--total-transactions=0). Exiting.");
            return;
        }

        // Acquire the default Metal device (Apple GPU on Apple Silicon).
        let device = Device::system_default().expect("No Metal-capable GPU found!");
        let config = resolve_chunk_transactions(cli, &device);

        // Per-chunk byte sizes for major buffer classes.
        let chunk_f32_bytes = config.chunk_transactions as u128 * std::mem::size_of::<f32>() as u128;
        let chunk_u32_bytes = config.chunk_transactions as u128 * std::mem::size_of::<u32>() as u128;
        let score_bytes = config.chunk_transactions as u128 * std::mem::size_of::<ScoreOutput>() as u128;

        // Stage B emits one partial record per threadgroup.
        let partial_groups = config.chunk_transactions.div_ceil(THREADGROUP_SIZE);
        let partial_metrics_bytes = partial_groups as u128 * std::mem::size_of::<PartialMetrics>() as u128;
        let partial_hist_bytes = partial_groups as u128 * config.score_bins as u128 * std::mem::size_of::<u32>() as u128;

        let max_buffer = device.max_buffer_length() as u128;
        // Proactively fail if any single buffer would exceed device limits.
        for (name, bytes) in [
            ("features", chunk_f32_bytes),
            ("labels", chunk_u32_bytes),
            ("score_output", score_bytes),
            ("partial_metrics", partial_metrics_bytes),
            ("partial_hist", partial_hist_bytes),
            ("params", std::mem::size_of::<KernelParams>() as u128),
        ] {
            if bytes > max_buffer {
                eprintln!(
                    "Buffer '{}' size {:.3} GB exceeds device max {:.3} GB. Reduce --chunk-transactions.",
                    name,
                    bytes as f64 / 1e9,
                    max_buffer as f64 / 1e9
                );
                std::process::exit(1);
            }
        }

        let total_chunks = config
            .total_transactions
            .div_ceil(config.chunk_transactions);

        println!("============================================================");
        println!(" Lesson 07: Credit Card Fraud Detector");
        println!("============================================================");
        println!("GPU:                 {}", device.name());
        println!("Mode:                {}", config.mode.as_str());
        println!("Validation:          {}", config.validation.as_str());
        println!("CPU baseline:        {}", config.compare_cpu.as_str());
        println!(
            "Total tx:            {} ({:.2} million)",
            config.total_transactions,
            config.total_transactions as f64 / 1e6
        );
        if config.chunk_auto {
            match config.detected_ram_bytes {
                Some(ram) => println!(
                    "System RAM detected: {:.2} GB (using {:.0}% target)",
                    ram as f64 / 1e9,
                    config.memory_fraction * 100.0
                ),
                None => println!(
                    "System RAM detected: unavailable (fallback auto chunking at {:.0}% target)",
                    config.memory_fraction * 100.0
                ),
            }
            println!(
                "Chunk tx:            {} ({:.2} million, auto)",
                config.chunk_transactions,
                config.chunk_transactions as f64 / 1e6
            );
        } else {
            println!(
                "Chunk tx:            {} ({:.2} million, manual)",
                config.chunk_transactions,
                config.chunk_transactions as f64 / 1e6
            );
        }
        println!("Total chunks:        {}", total_chunks);
        println!("Threshold:           {:.3}", config.threshold);
        println!("Score bins:          {}", config.score_bins);
        println!();

        let options = CompileOptions::new();
        // Compile Metal kernels from embedded source at runtime.
        let library = device
            .new_library_with_source(SHADER_SOURCE, &options)
            .expect("Failed to compile Metal shader source");

        let score_func = library
            .get_function("score_transactions", None)
            .expect("Missing score_transactions");
        let reduce_func = library
            .get_function("reduce_metrics", None)
            .expect("Missing reduce_metrics");

        let score_pipeline = device
            .new_compute_pipeline_state_with_function(&score_func)
            .expect("Failed creating score pipeline");
        let reduce_pipeline = device
            .new_compute_pipeline_state_with_function(&reduce_func)
            .expect("Failed creating reduce pipeline");

        // Ensure selected threadgroup size is supported by both kernels.
        if score_pipeline.max_total_threads_per_threadgroup() < THREADGROUP_SIZE {
            eprintln!(
                "Score pipeline max threads/threadgroup ({}) too small for {}",
                score_pipeline.max_total_threads_per_threadgroup(),
                THREADGROUP_SIZE
            );
            std::process::exit(1);
        }
        if reduce_pipeline.max_total_threads_per_threadgroup() < THREADGROUP_SIZE {
            eprintln!(
                "Reduce pipeline max threads/threadgroup ({}) too small for {}",
                reduce_pipeline.max_total_threads_per_threadgroup(),
                THREADGROUP_SIZE
            );
            std::process::exit(1);
        }

        let gpu = GpuPipelines {
            command_queue: device.new_command_queue(),
            score_pipeline,
            reduce_pipeline,
        };

        // Single mode uses one slot, double mode uses ping-pong slots.
        let slot_count = match config.mode {
            Mode::Single => 1,
            Mode::Double => 2,
        };

        // Allocate all buffers up-front to avoid per-chunk allocation overhead.
        let mut slots = Vec::with_capacity(slot_count);
        for _ in 0..slot_count {
            slots.push(SlotBuffers {
                // Feature columns (f32 each).
                amounts: device.new_buffer(chunk_f32_bytes as u64, MTLResourceOptions::StorageModeShared),
                hours: device.new_buffer(chunk_f32_bytes as u64, MTLResourceOptions::StorageModeShared),
                distance_km: device.new_buffer(chunk_f32_bytes as u64, MTLResourceOptions::StorageModeShared),
                is_card_present: device.new_buffer(chunk_f32_bytes as u64, MTLResourceOptions::StorageModeShared),
                mcc_risk: device.new_buffer(chunk_f32_bytes as u64, MTLResourceOptions::StorageModeShared),
                velocity_1h: device.new_buffer(chunk_f32_bytes as u64, MTLResourceOptions::StorageModeShared),
                country_mismatch: device.new_buffer(chunk_f32_bytes as u64, MTLResourceOptions::StorageModeShared),
                device_change: device.new_buffer(chunk_f32_bytes as u64, MTLResourceOptions::StorageModeShared),
                // Ground-truth labels generated on CPU.
                actual_labels: device.new_buffer(chunk_u32_bytes as u64, MTLResourceOptions::StorageModeShared),
                // Stage A output for every row.
                score_output: device.new_buffer(score_bytes as u64, MTLResourceOptions::StorageModeShared),
                // Stage B partial reductions.
                partial_metrics: device.new_buffer(partial_metrics_bytes as u64, MTLResourceOptions::StorageModeShared),
                partial_hist: device.new_buffer(partial_hist_bytes as u64, MTLResourceOptions::StorageModeShared),
                // Small constants block read by kernels.
                params: device.new_buffer(
                    std::mem::size_of::<KernelParams>() as u64,
                    MTLResourceOptions::StorageModeShared,
                ),
            });
        }

        // Execute selected GPU scheduling strategy.
        let gpu_result = match config.mode {
            Mode::Single => run_single(&config, &gpu, &slots),
            Mode::Double => run_double(&config, &gpu, &slots),
        };

        let (gpu_stats, gpu_totals) = match gpu_result {
            Ok(v) => v,
            Err(e) => {
                eprintln!("Execution failed: {e}");
                std::process::exit(1);
            }
        };

        let cpu_baseline = if config.compare_cpu == CompareCpu::On {
            // Run after GPU path so startup compilation cost does not pollute CPU timing.
            Some(run_cpu_baseline(&config))
        } else {
            None
        };

        print_summary(&config, gpu_stats, &gpu_totals, cpu_baseline);
    });
}
